#!/bin/sh
if [ -z ${JAVA_HOME+x} ]; then JAVA_CMD="java"; else JAVA_CMD=$JAVA_HOME/bin/java; fi
INSTALL_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
$JAVA_CMD -Dfile.encoding=UTF-8 -cp $INSTALL_DIR/!!artifactId!!-!!version!!.jar ru.factsearch.Query ${1+"$@"}
